CREATE DATABASE SA;

CREATE TABLE CLIENT (
    ID INT primary key NOT NULL AUTO_INCREMENT,
    EMAIL varchar(50) UNIQUE
);

CREATE TABLE SENTIMENT (
    ID INT primary key NOT NULL AUTO_INCREMENT,
    TEXTE varchar(50),
    TYPE varchar(10),
    CLIENT_ID INT,
    CONSTRAINT client_fk FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);